[package]
name = "vramblk"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ctrlc = { version = "3.4.4", features = ["termination"] }
libc = "0.2.153"
opencl3 = "0.9.5"
parse-size = { version = "1.0.0", features = ["std"] }
vblk = "0.1.2"
